spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_DEV}
        secret-key: ${AWS_SECRET_KEY_DEV}
      region:
        static: ${AWS_REGION_DEV}
      stack:
        auto: false
      sqs:
        queue:
          name: ${AWS_SQS_NOTIFICATION_NAME_DEV}
          url: ${AWS_SQS_NOTIFICATION_URL_DEV}

    firebase:
      credentials:
        uri: ${FIREBASE_URI}
      config:
        path: ${FIREBASE_PATH}

jwt:
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
