#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_DEV}
#      secretKey: ${AWS_SECRET_KEY_DEV}
#    region:
#      static: ${AWS_REGION_DEV}
#    stack:
#      auto: false
#    sqs:
#      notification:
#        name: ${AWS_SQS_NOTIFICATION_NAME_DEV}
#        url: ${AWS_SQS_NOTIFICATION_URL_DEV}
#      api:
#        name: ${AWS_SQS_API_NAME_DEV}
#        url: ${AWS_SQS_API_URL_DEV}
#
#  firebase:
#    credentials:
#      uri: ${FIREBASE_URI}
#    config:
#      path: ${FIREBASE_PATH}
#
#jwt:
#  secret: ${JWT_SECRET_DEV}
#
#slack:
#  webhook:
#    url: ${SLACK_WEBHOOK_URL_DEV}
