spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL_DEV}
    username: ${AWS_RDS_USERNAME_DEV}
    password: ${AWS_RDS_PASSWORD_DEV}

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${AWS_ELASTICACHE_HOST_DEV}
      port: ${AWS_ELASTICACHE_PORT_DEV}


#cloud:
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_DEV}
#      secretKey: ${AWS_SECRET_KEY_DEV}
#    region:
#      static: ${AWS_REGION_DEV}
#    stack:
#      auto: false
#    sqs:
#      notification:
#        name: ${AWS_SQS_NOTIFICATION_NAME_DEV}
#        url: ${AWS_SQS_NOTIFICATION_URL_DEV}
#      api:
#        name: ${AWS_SQS_API_NAME_DEV}
#        url: ${AWS_SQS_API_URL_DEV}
#
#  firebase:
#    credentials:
#      uri: ${FIREBASE_URI}
#    config:
#      path: ${FIREBASE_PATH}
#
#jwt:
#  secret: ${JWT_SECRET_DEV}
#
#slack:
#  webhook:
#    url: ${SLACK_WEBHOOK_URL_DEV}
