spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_DEV}
        secret-key: ${AWS_SECRET_KEY_DEV}
      region:
        static: ${AWS_REGION_DEV}
      stack:
        auto: false
      sqs:
        queue:
          name: ${AWS_SQS_NOTIFICATION_NAME_DEV}

    firebase:
      auth:
        uri: https://www.googleapis.com/auth/cloud-platform
      message:
        uri: ${FIREBASE_MESSAGING_URI}
      config:
        path: ${FIREBASE_PATH}

#jwt:
#  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
