spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plu?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnection=true
    username: plu
    password: plu

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      #data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_DEV}
        secret-key: ${AWS_SECRET_KEY_DEV}
      region:
        static: ${AWS_REGION_DEV}
      stack:
        auto: false
      sqs:
        queue:
          name: ${AWS_SQS_NOTIFICATION_NAME_DEV}
          url: ${AWS_SQS_NOTIFICATION_URL_DEV}

    firebase:
      credentials:
        uri: ${FIREBASE_URI}
      config:
        path: ${FIREBASE_PATH}

#jwt:
#  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
#
#slack:
#  webhook:
#    url: ${SLACK_WEBHOOK_URL_DEV}
