spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${AWS_RDS_URL_DEV}
    username: ${AWS_RDS_USERNAME_DEV}
    password: ${AWS_RDS_PASSWORD_DEV}

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      #data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    redis:
      host: ${AWS_ELASTICACHE_HOST_DEV}
      port: ${AWS_ELASTICACHE_PORT_DEV}


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_DEV}
        secret-key: ${AWS_SECRET_KEY_DEV}
      region:
        static: ${AWS_REGION_DEV}
      stack:
        auto: false
      sqs:
        queue:
          name: ${AWS_SQS_NOTIFICATION_NAME_DEV}

    firebase:
      auth:
        uri: https://www.googleapis.com/auth/cloud-platform
      message:
        uri: ${FIREBASE_MESSAGING_URI}
      config:
        path: ${FIREBASE_PATH}

jwt:
  secret: ${JWT_SECRET_DEV}
