# This is a basic workflow to help you get started with Actions
# pr 올렸을 때 trigger
name: api-pr-check-dev

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
    paths:
      - plu-api/**
      - plu-common/**
      - plu-domain/**
      - plu-external/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: plu-api/src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.API_YML }}" > application.yml
          echo "${{ secrets.API_DEV_YML }}" > application-dev.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew plu-api:bootJar -x test
        shell: bash