name: notification-pr-check-dev

# Controls when the workflow will run
on:
  pull_request:
    branches: [ develop ]
    paths:
      - .github/workflows/**
      - plu-notification/**
      - plu-common/**
      - plu-domain/**
      - plu-external/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create secret files
        working-directory: plu-notification/src/main/resources
        run: |
          touch application.yml
          touch application-dev.yml
          echo "${{ secrets.NOTIFICATION_YML }}" > application.yml
          echo "${{ secrets.NOTIFICATION_DEV_YML }}" > application-dev.yml
          
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" > ./firebase/plu-firebase-config.json
          sed -i 's/#/"/g' ./firebase/plu-firebase-config.json

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew plu-notification:bootJar -x test
        shell: bash